# define all required variables for CI, so we can limit the configuration and logic within GHA to test more of the CI process locally

[env]
RAILPACK_MISE_VERSION = "{{read_file(path='core/mise/version.txt')}}"
PRODUCTION_CONTAINER_REGISTRY = "ghcr.io"
PRODUCTION_GITHUB_REPOSITORY = "railwayapp/railpack"
PRODUCTION_MISE_TAG = "mise-${RAILPACK_MISE_VERSION}"

PRODUCTION_BUILDER_IMAGE_NAME = "${PRODUCTION_CONTAINER_REGISTRY}/${PRODUCTION_GITHUB_REPOSITORY}-builder"
PRODUCTION_BUILDER_IMAGE_REF = "${PRODUCTION_BUILDER_IMAGE_NAME}:${PRODUCTION_MISE_TAG}"

PRODUCTION_RUNTIME_IMAGE_NAME = "${PRODUCTION_CONTAINER_REGISTRY}/${PRODUCTION_GITHUB_REPOSITORY}-runtime"
PRODUCTION_RUNTIME_IMAGE_REF = "${PRODUCTION_RUNTIME_IMAGE_NAME}:${PRODUCTION_MISE_TAG}"

PRODUCTION_FRONTEND_IMAGE_NAME = "${PRODUCTION_CONTAINER_REGISTRY}/${PRODUCTION_GITHUB_REPOSITORY}-frontend"

[settings]
# intermittent failures on CI are a big time suck, let's be generous with our installation retries
http_retries = 5

# require URLs to be present in the mise.lockfile to ensure there is consistent versions used across CI runs
locked = true