[env]
BUILDKIT_HOST = "docker-container://buildkit"

_.path = './bin'

[tools]
go = "1.26"
golangci-lint = "latest"
bun = "1.3"

[settings]
experimental = true
# without this, navigating into various examples/ will output an annoying warning
idiomatic_version_file_enable_tools = ["python", "node", "ruby"]
# ensures homebrew go, etc doesn't take precedence
activate_aggressive = true
env_shell_expand = true

[tasks.setup]
run = [
  "mise install",
  "mise run run-buildkit-container || true",
]

[tasks.run-buildkit-container]
run = "docker run --rm --privileged -d --name buildkit -e BUILDKIT_DEBUG=1 moby/buildkit:latest"

[tasks.cli]
run = "go run cmd/cli/main.go"

# run a go debugging against the CLI entrypoint
[tasks.debug-cli]
run = "dlv debug github.com/railwayapp/railpack/cmd/cli --"

# build the CLI binary (`./bin/railpack`) for local use outside the project
[tasks.build]
run = "go build -o bin/railpack cmd/cli/main.go"

[tasks.clean]
run = [
  "rm -rf bin dist docs/dist",
  # clean up buildkit cache, avoids cached layers from being used
  "docker exec buildkit buildctl prune",
  "rm -f *.test",
  # stop all railpack containers
  "docker stop $(docker ps -q --filter name=railpack)",
  # remove all images created by the integration test suite
  "docker images 'railpack-test-*' -q | xargs -r docker rmi -f",
  # remove images created by manually running `railpack build` against a project example
  "find examples -name test.json -exec dirname {} \\; | xargs -n 1 basename | xargs -r -I {} docker rmi -f {}",
  "go clean -testcache",
  "mise cache clear",
  "rm -rf /tmp/railpack",
]

# if a example folder does not have a test.json file, it will be skipped
[tasks.examples-without-tests]
run = "find examples -mindepth 1 -maxdepth 1 -type d ! -exec [ -f \"{}/test.json\" ] \\; -print "

# run unit tests
[tasks.test]
run = "go test -short ./..."

# Runs *all* integration tests. It is extremely slow, do not run this locally.
# Instead, only run the test that you are currently working on:
# `mise run test-integration -- -run "TestExamplesIntegration/config-file"`
[tasks.test-integration]
run = "go test -v ./integration_tests"

# run integration test for the example directory you're currently in
[tasks.test-integration-cwd]
run = """
if [[ ! "$MISE_ORIGINAL_CWD" =~ /examples/ ]]; then
  echo "Error: must be run from within an examples/ directory"
  exit 1
fi

example_name=$(basename "$MISE_ORIGINAL_CWD")
echo "Running integration test for: $example_name"
go test -v ./integration_tests -run "TestExamplesIntegration/$example_name"
"""

[tasks.run-example-cwd]
run = """
if [[ ! "$MISE_ORIGINAL_CWD" =~ /examples/ ]]; then
  echo "Error: must be run from within an examples/ directory"
  exit 1
fi

example_name=$(basename "$MISE_ORIGINAL_CWD")
mise run cli build $MISE_ORIGINAL_CWD --show-plan --progress=plain --env MISE_VERBOSE=1
echo "Running example: 'docker run $example_name'"
"""

# update all test snapshots, if you've updated a example/ project, run this to update the snapshots
[tasks.test-update-snapshots]
run = [
  "UPDATE_SNAPS=true go test -short ./...",
  "find . -type d -name '__snapshots__' -exec git add -- {} +",
  "echo 'test: update snapshots' > $(git rev-parse --git-dir)/COMMIT_EDITMSG",
]

# modernize code using the latest Go fixers
[tasks.fix]
description = "Modernize code using the latest Go fixers"
run = ["golangci-lint run --fix",
  "go fix ./..."]

# linting, formatting, and static analysis
[tasks.check]
run = ["go vet ./...", "go fmt ./...", "golangci-lint run", "go mod verify"]

[tasks.upgrade]
description = "Upgrade all Go and Mise packages"
run = [
  # ensures we are using the latest version of mise locally
  "mise self-update",
  # updates lockfiles
  "mise upgrade --local",
  # get latest go packages
  "go get -u ./...",
  "go mod tidy",
  # update packages, respecting semver
  "cd docs && bun update"
]

# build docs for production
[tasks.docs-build]
dir = "docs"
run = ["bun install --frozen-lockfile", "bun run build"]

[tasks.docs-dev]
dir = "docs"
run = ["bun install", "bun run dev"]

[tasks.image-builder-build]
run = "docker build --build-arg MISE_VERSION=$RAILPACK_MISE_VERSION -f images/debian/build/Dockerfile -t railpack-builder:local ."

[tasks.image-runtime-build]
run = "docker build -f images/debian/runtime/Dockerfile -t railpack-runtime:local ."